package com.moregood.kit.utils;

public interface Constans {
    String IV_SHORTCUT_WIDTH_120 = "?x-oss-process=image/resize,h_120,w_120";
    String IV_SHORTCUT_WIDTH_200 = "?x-oss-process=image/resize,h_200,w_200";
    String IV_SHORTCUT_WIDTH_300 = "?x-oss-process=image/resize,h_300,w_300";
    String IV_SHORTCUT_WIDTH_500 = "?x-oss-process=image/resize,h_300,w_500";
    String IV_SHORTCUT_WIDTH_1000 = "?x-oss-process=image/resize,h_800,w_1000";

    String USER_TYPE = "userType";
    String STORE_ID = "storeId";
    String PRODUCT_ID = "productId";
    String ORDER_ID = "orderId";
    String CLOSE_DIALOG = "closeDialog";
    String MY_COMMENT = "myComment";
    String COMMENT_ID = "commentId";
    String DEL_COMMENT = "delComment";
    String POSITION = "position";
    String FOLLOW_COMMENT_SUCCESS = "followCommentSuccess";
    int MAX_100 = 100;
    int MAX_140 = 140;
    int MAX_200 = 200;
    int MAX_UPLOAD_IMG = 6;
    int MIN_DATUM = 1200;
    int QUALITY_90 = 90;
    String NOTICE_LIST = "noticeList";
    String IS_NEED = "isNeed";
    String COMMENT_RIDER = "commentRider";
    String COMMENT_RIDER_SUCCESS = "commentRiderSuccess";//评价骑手成功
    String COMMENT_ORDER_SUCCESS = "commentOrderSuccess";//评价订单成功
    int GOOD_COMMENT = 1;
    int BAD_COMMENT = 2;
    int ANONYMOUS = 1;//表示匿名
    int NO_ANONYMOUS = 0;//表示不匿名
    int TYPE_SHOP = 1;//店铺
    int TYPE_ADVERT = 2;//广告
    int VIEW_HOLDER_TYPE_SHOP = 0;//店铺
    int VIEW_HOLDER_TYPE_ADVERT = 1;//广告
    String MSG_SOURCE = "msgSource";
    int MSG_SOURCE_MALL = 1;
    int MSG_SOURCE_MERCHANT = 2;
    int MSG_SOURCE_RIDER = 3;
    int MSG_SOURCE_KEFU = 4;
    String IS_FIRST = "isFirst";
    String COUPON_PUSH_TYPE = "couponPushType";
    String COUPON_ID = "couponId";
    String COUPON = "coupon";
    String STATE = "state";
    String IS_NEED_SHOW = "isNeedShow";
    String START_TIME = "startTime";
    String WAIT_COMMENT_ORDER_TIP = "waitCommentOrderTip";
    String RICH_TEXT = "richText";
    String COMBINDED_ORDER_TIP = "combindedOrderTip";
    int USER_TYPE_TAKEAWAY = 1;
    int USER_TYPE_GROUP_BUG = 2;
    String LBS = "lbs";
    String DEL_ADDRESS = "delAddress";
    String DEL_EDIT_ADDRESS = "delEditAddress";
    String IS_ALL_GESTURES_ENABLED = "isAllGesturesEnabled";
    String TYPE = "type";
    String ORDER_REFRESH = "order_refresh";
    String TIME = "time";//后台时间
    String REFRESH_FOREGROUND = "refresh_foreground";//后台时间

}
